#!/usr/bin/env python3
"""
Generate Tech Fact & Developer Tip Shorts for Auto Clipper Shorts.
Uses Neural Text-to-Speech (edge-tts) for high-energy tech narration,
generates dynamic neon karaoke subtitles, tech badges, and audio visualizers.
"""

import os
import sys
import json
import random
import shutil
import asyncio
from pathlib import Path

# Add project root to sys.path
WORKSPACE_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(WORKSPACE_DIR))

try:
    import edge_tts
except ImportError:
    edge_tts = None

from main import (
    create_word_timestamps_from_segment,
    generate_karaoke_ass_subtitles,
    render_studio_visualizer_short,
    upload_to_youtube,
    load_json,
    save_json,
    HISTORY_PATH,
    log,
    OUTPUT_DIR
)

FALLBACK_SERIES_DATABASE = [
    {
        "series_id": "underwater_internet",
        "topic": "HOW THE INTERNET ACTUALLY WORKS",
        "badge_base": "INTERNET SECRETS 🌐",
        "next_topic_teaser": "the secret Linux kernel superpowers that power ninety percent of cloud servers",
        "total_parts": 3,
        "parts": [
            {
                "part_number": 1,
                "title": "How 99% of the Internet Flows Underwater • Part 1 🌊 #Shorts #TechShorts",
                "badge": "INTERNET SECRETS • PART 1",
                "voice": "en-US-ChristopherNeural",
                "tags": ["techshorts", "technology", "internet", "cables", "networking", "shorts"],
                "script": (
                    "Did you know that over ninety nine percent of all international internet traffic does not travel through satellites in space, "
                    "but through massive fiber optic cables resting on the pitch black ocean floor? "
                    "There are over five hundred active subsea cables stretching eight hundred thousand miles across the Earth, connecting every continent. "
                    "These glass lines are barely as thick as a garden hose, yet they transmit petabits of financial transactions, streaming video, and cloud data every single millisecond. "
                    "Here is the crazy part. If a deep sea anchor accidentally snags one of these cables, or an underwater earthquake shifts the seabed, "
                    "entire nations can instantly lose their internet connection overnight! "
                    "In Part 2, we uncover how subsea cables survive immense oceanic pressure and why sharks constantly bite them. "
                    "Like and subscribe so you don't miss Part 2!"
                )
            },
            {
                "part_number": 2,
                "title": "Why Sharks Bite Undersea Cables & Optical Repeaters • Part 2 🦈 #Shorts",
                "badge": "INTERNET SECRETS • PART 2",
                "voice": "en-US-ChristopherNeural",
                "tags": ["techshorts", "technology", "internet", "cables", "engineering", "shorts"],
                "script": (
                    "Welcome back to Part 2 of How the Internet Actually Works! "
                    "Why do subsea fiber optic cables require ten thousand volts of electricity running directly through the ocean? "
                    "Because as light signals travel thousands of miles through glass fibers, the photons attenuate and fade. "
                    "Every fifty miles along the seabed, engineers install massive titanium optical repeaters containing erbium-doped laser amplifiers to boost the light signals back to full strength! "
                    "However, the magnetic fields generated by this high-voltage power line confuse deep-sea sharks, causing them to aggressively bite the cables! "
                    "Engineers now wrap every line in double-layered Kevlar and steel armor. "
                    "In Part 3, we reveal how hundred-million-dollar robotic ships laser weld snapped fibers miles under the ocean. "
                    "Drop a like and subscribe for Part 3!"
                )
            },
            {
                "part_number": 3,
                "title": "How Robotic Ships Repair Snapped Undersea Fibers • Part 3 🚢 #Shorts",
                "badge": "INTERNET SECRETS • PART 3",
                "voice": "en-US-ChristopherNeural",
                "tags": ["techshorts", "technology", "internet", "cables", "engineering", "shorts"],
                "script": (
                    "Welcome back to the finale of How the Internet Actually Works! "
                    "When a deep sea fiber optic cable snaps thousands of feet below the surface, how do engineers fix it without draining the ocean? "
                    "They deploy specialized hundred-million-dollar cable ships equipped with heavy-duty robotic submarines. "
                    "These robots dive into the freezing abyss, slice into the seabed with high pressure water jets, and grapple both severed ends of the cable. "
                    "They hoist the lines to the ship's cleanroom deck, where technicians meticulously laser weld individual glass fibers thinner than a human hair! "
                    "And that is the invisible engineering keeping our planet connected. "
                    "In our next series, we'll be breaking down the secret Linux kernel superpowers that power ninety percent of cloud servers, so stay tuned and make sure to like and subscribe!"
                )
            }
        ]
    },
    {
        "series_id": "linux_superpowers",
        "topic": "LINUX KERNEL & TERMINAL SECRETS",
        "badge_base": "LINUX HACKS 🐧",
        "next_topic_teaser": "how modern cryptography and zero-knowledge proofs protect global privacy",
        "total_parts": 3,
        "parts": [
            {
                "part_number": 1,
                "title": "The Secret Linux Shortcut Every Developer Needs • Part 1 🐧 #Shorts",
                "badge": "LINUX HACKS • PART 1",
                "voice": "en-US-GuyNeural",
                "tags": ["linux", "terminal", "bash", "developer", "codingtips", "shorts"],
                "script": (
                    "Stop frantically hitting the up arrow fifty times just to find a terminal command you ran three weeks ago! "
                    "Every programmer needs to know this secret Linux superpower. "
                    "Inside any bash or zsh terminal, just press Control plus R on your keyboard. "
                    "This instantly activates the recursive history search engine. "
                    "The moment you start typing a single keyword like docker, git, or ssh, Linux instantly searches your entire shell history and auto-completes your longest, most complicated command with zero typos! "
                    "If you press Control plus R again, it cycles backwards through every past variation you ever executed. "
                    "In Part 2, we uncover how the Linux slash proc filesystem lets you inspect live computer RAM without a debugger. "
                    "Drop a like and subscribe for Part 2!"
                )
            },
            {
                "part_number": 2,
                "title": "The Magic of Linux /proc & Live RAM Files • Part 2 ⚡ #Shorts",
                "badge": "LINUX HACKS • PART 2",
                "voice": "en-US-GuyNeural",
                "tags": ["linux", "terminal", "sysadmin", "coding", "developer", "shorts"],
                "script": (
                    "Welcome back to Part 2 of Linux Kernel Secrets! "
                    "Did you know that in Linux, literally everything in your operating system is treated as a plain text file? "
                    "If you navigate to slash proc on your machine, you are looking directly into your live computer RAM. "
                    "You can inspect active CPU temperatures, memory allocations, and even inject data into running processes without opening a debugger! "
                    "Combine this with the Unix pipe operator, and you can stream terabytes of data between programs without ever touching your hard drive. "
                    "In Part 3, we reveal the terrifying Linux Out-Of-Memory Killer that secretly terminates background apps when RAM runs low. "
                    "Hit like and subscribe for Part 3!"
                )
            },
            {
                "part_number": 3,
                "title": "The Terrifying Linux OOM Killer Algorithm • Part 3 💀 #Shorts",
                "badge": "LINUX HACKS • PART 3",
                "voice": "en-US-GuyNeural",
                "tags": ["linux", "kernel", "sysadmin", "coding", "developer", "shorts"],
                "script": (
                    "Welcome back to the finale of Linux Kernel Secrets! "
                    "What happens when your server runs completely out of RAM? "
                    "Linux doesn't crash or freeze. Instead, it unleashes a brutal kernel algorithm known as the Out Of Memory Killer! "
                    "The OOM Killer scans every active process on your machine, calculates a ruthless badness score based on memory usage and runtime privilege, and sends an uncatchable kill signal nine to instantly execute the biggest offender! "
                    "This savage efficiency is why Linux powers ninety percent of the world's cloud servers and supercomputers. "
                    "In our next series, we'll be exploring how modern cryptography and zero-knowledge proofs protect global privacy, so stay tuned and make sure to like and subscribe!"
                )
            }
        ]
    },
    {
        "series_id": "modern_cryptography",
        "topic": "THE CRYPTOGRAPHY REVOLUTION",
        "badge_base": "CYBERSECURITY 🛡️",
        "next_topic_teaser": "why zero point one plus zero point two is not zero point three and the space rockets it exploded",
        "total_parts": 3,
        "parts": [
            {
                "part_number": 1,
                "title": "How SSH Logs You In Without Sending Your Password • Part 1 🔐 #Shorts",
                "badge": "CYBERSECURITY • PART 1",
                "voice": "en-US-ChristopherNeural",
                "tags": ["cybersecurity", "ssh", "encryption", "infosec", "linux", "shorts"],
                "script": (
                    "How do SSH keys log you into top secret cloud servers across the globe without ever transmitting your password across the internet? "
                    "It all comes down to an ingenious mathematical trapdoor known as asymmetric cryptography. "
                    "When you generate an SSH key pair, your computer creates a public key and a private key. "
                    "You place the public key on the remote server, while keeping your private key heavily guarded on your laptop. "
                    "When you log in, the server never asks for your secret password. "
                    "Instead, the server generates a random cryptographic challenge, locks it with your public key, and transmits it to your computer. "
                    "In Part 2, we uncover why even a billion supercomputers running for trillions of years cannot crack elliptic curve math. "
                    "Drop a like and subscribe for Part 2!"
                )
            },
            {
                "part_number": 2,
                "title": "Why Supercomputers Cannot Crack Elliptic Curves • Part 2 🛡️ #Shorts",
                "badge": "CYBERSECURITY • PART 2",
                "voice": "en-US-ChristopherNeural",
                "tags": ["cybersecurity", "encryption", "math", "infosec", "techfacts", "shorts"],
                "script": (
                    "Welcome back to Part 2 of The Cryptography Revolution! "
                    "Once a cryptographic challenge is locked with your public key, why can't a hacker intercept and solve it? "
                    "Because modern encryption is based on the mathematical difficulty of elliptic curve discrete logarithms and prime factorization. "
                    "Multiplying points on an algebraic curve is lightning fast in one direction, but reversing the calculation without your private key requires checking billions of combinations! "
                    "Even if you combined all the supercomputers on Earth, cracking a modern two hundred fifty six bit elliptic curve key would take longer than the age of the universe! "
                    "In Part 3, we reveal Zero-Knowledge Proofs and how they prove secret passwords without revealing a single letter. "
                    "Like and subscribe for Part 3!"
                )
            },
            {
                "part_number": 3,
                "title": "Zero-Knowledge Proofs: Proving Secrets Without Sharing Them • Part 3 🤯 #Shorts",
                "badge": "CYBERSECURITY • PART 3",
                "voice": "en-US-ChristopherNeural",
                "tags": ["cybersecurity", "zkp", "encryption", "privacy", "math", "shorts"],
                "script": (
                    "Welcome back to the finale of The Cryptography Revolution! "
                    "Imagine proving you know the secret password to a top-secret vault without ever saying the password out loud or writing it down. "
                    "This mathematical miracle is called a Zero-Knowledge Proof! "
                    "Using advanced polynomial equations and homomorphic commitments, your computer can mathematically prove it possesses a secret answer with ninety nine point nine nine percent certainty, without leaking even a single bit of information! "
                    "Zero-Knowledge Proofs are now revolutionizing private digital identity, decentralized finance, and confidential voting systems worldwide. "
                    "In our next series, we'll be discussing why zero point one plus zero point two is not zero point three and the space rockets it exploded, so stay tuned and make sure to like and subscribe!"
                )
            }
        ]
    },
    {
        "series_id": "floating_point_math",
        "topic": "FLOATING POINT SECRETS & DISASTERS",
        "badge_base": "CS DEEP DIVE 💻",
        "next_topic_teaser": "the crazy true history of the first computer bug and the moth that changed computing",
        "total_parts": 3,
        "parts": [
            {
                "part_number": 1,
                "title": "Why 0.1 + 0.2 Is NOT 0.3 In Computer Science • Part 1 🤯 #Shorts",
                "badge": "CS DEEP DIVE • PART 1",
                "voice": "en-US-EricNeural",
                "tags": ["programming", "coding", "computerscience", "math", "python", "shorts"],
                "script": (
                    "If you open your browser console, Python terminal, or C plus plus compiler right now and calculate zero point one plus zero point two, "
                    "you will not get zero point three! "
                    "Instead, you get zero point three zero zero zero zero zero zero zero zero zero zero zero zero zero zero four! "
                    "This is not a bug in your computer, it is a fundamental mathematical law of how microprocessors work. "
                    "Modern computers do not count in base ten decimals like humans. They use base two binary floating point numbers under the IEEE seven fifty four standard. "
                    "In binary math, fractions like one tenth create an infinite repeating sequence, exactly like trying to write one third in decimal! "
                    "In Part 2, we explore how this exact floating point error blew up a five hundred million dollar space rocket thirty seven seconds after launch. "
                    "Hit like and subscribe for Part 2!"
                )
            },
            {
                "part_number": 2,
                "title": "The $500M Floating Point Rocket Crash • Part 2 🚀 #Shorts",
                "badge": "CS DEEP DIVE • PART 2",
                "voice": "en-US-EricNeural",
                "tags": ["programming", "engineering", "space", "rockets", "computerscience", "shorts"],
                "script": (
                    "Welcome back to Part 2 of Floating Point Disasters! "
                    "In nineteen ninety six, the European Space Agency launched the Ariane Five rocket carrying a five hundred million dollar scientific payload. "
                    "Just thirty seven seconds after liftoff, the rocket suddenly flipped ninety degrees and disintegrated in a massive fireball! "
                    "The post-crash investigation revealed that the guidance software tried to convert a sixty-four bit floating point number representing horizontal velocity into a sixteen bit signed integer. "
                    "The number was larger than thirty two thousand seven hundred sixty seven, causing an integer overflow exception that paralyzed the onboard flight computers! "
                    "In Part 3, we reveal how a floating point clock drift caused a tragic military missile defense failure. "
                    "Like and subscribe for Part 3!"
                )
            },
            {
                "part_number": 3,
                "title": "The 0.34 Second Clock Drift Disaster • Part 3 ⚠️ #Shorts",
                "badge": "CS DEEP DIVE • PART 3",
                "voice": "en-US-EricNeural",
                "tags": ["programming", "computerscience", "engineering", "history", "shorts"],
                "script": (
                    "Welcome back to the finale of Floating Point Disasters! "
                    "In nineteen ninety one, a Patriot missile battery failed to intercept an incoming Scud missile due to a tiny rounding error. "
                    "The system's internal clock measured time in tenths of a second using a twenty-four bit register. "
                    "Because one tenth has an infinite repeating binary expansion, the system lost zero point zero zero zero zero zero zero zero nine five seconds every single tick! "
                    "After one hundred hours of continuous operation, that tiny error accumulated into a zero point thirty-four second delay, causing the radar to look over six hundred meters away from the actual incoming target! "
                    "And that is why numerical precision is a matter of life and death in computer engineering. "
                    "In our next series, we'll be discussing the crazy true history of the very first computer bug, so stay tuned and make sure to like and subscribe!"
                )
            }
        ]
    },
    {
        "series_id": "first_computer_bug",
        "topic": "THE HISTORY & ANATOMY OF COMPUTER BUGS",
        "badge_base": "TECH HISTORY 📜",
        "next_topic_teaser": "how ninety nine percent of the global internet travels under the ocean",
        "total_parts": 3,
        "parts": [
            {
                "part_number": 1,
                "title": "The Crazy True Story of the First Computer Bug • Part 1 🪲 #TechShorts",
                "badge": "TECH HISTORY • PART 1",
                "voice": "en-US-GuyNeural",
                "tags": ["techhistory", "programming", "debugging", "computerscience", "shorts"],
                "script": (
                    "Have you ever wondered why software engineers call fixing a broken program debugging? "
                    "The origin story is completely literal and involves a real two-inch moth! "
                    "In nineteen forty seven, computer science pioneer Grace Hopper was working on the Harvard Mark Two electromechanical computer for the United States Navy. "
                    "Suddenly, the massive sixteen-ton machine stopped processing calculations correctly. "
                    "The engineering team spent hours meticulously inspecting thousands of electrical relays across the entire computer until they finally inspected relay number seventy in panel F. "
                    "Trapped between the metal contact points was an actual dead moth that was short-circuiting the electrical signal! "
                    "In Part 2, we uncover how a computer bug nearly triggered World War Three during the Cold War. "
                    "Like and subscribe so you don't miss Part 2!"
                )
            },
            {
                "part_number": 2,
                "title": "The Satellite Bug That Nearly Started WWIII • Part 2 🛰️ #Shorts",
                "badge": "TECH HISTORY • PART 2",
                "voice": "en-US-GuyNeural",
                "tags": ["techhistory", "history", "computerscience", "bugs", "shorts"],
                "script": (
                    "Welcome back to Part 2 of Computer Bug History! "
                    "In nineteen eighty three, Soviet early-warning computers suddenly sounded an emergency siren, alerting officers that the United States had launched five nuclear intercontinental ballistic missiles! "
                    "Protocol demanded an immediate retaliatory nuclear strike. "
                    "However, duty officer Stanislav Petrov suspected a computer glitch because a real attack would involve hundreds of missiles, not just five. "
                    "He defied protocol and reported a false alarm. "
                    "Later investigations proved he was right: the early warning satellite software had misidentified high-altitude sunlight reflections off cloud tops as missile plumes! "
                    "In Part 3, we reveal the Year 2038 Unix Time Bomb that threatens millions of legacy servers. "
                    "Drop a like and subscribe for Part 3!"
                )
            },
            {
                "part_number": 3,
                "title": "The Year 2038 Unix Epoch Time Bomb • Part 3 ⏳ #Shorts",
                "badge": "TECH HISTORY • PART 3",
                "voice": "en-US-GuyNeural",
                "tags": ["techhistory", "y2k38", "linux", "programming", "shorts"],
                "script": (
                    "Welcome back to the finale of Computer Bug History! "
                    "On January nineteenth, twenty thirty-eight, millions of 32-bit computers worldwide will face a catastrophic digital rollover known as the Year 2038 Problem! "
                    "Unix systems store time as the number of seconds elapsed since January first, nineteen seventy, using a signed thirty-two bit integer. "
                    "At three fourteen AM UTC on that day, the counter will exceed two billion one hundred forty-seven million four hundred eighty-three thousand six hundred forty-seven seconds! "
                    "When it overflows into the negative sign bit, unpatched systems will suddenly believe it is December thirteenth, nineteen zero-one, causing power grids, medical devices, and embedded controllers to crash! "
                    "Software engineers are currently racing to upgrade all infrastructure to sixty-four bit timestamps. "
                    "In our next series, we'll be exploring how ninety nine percent of the global internet travels under the ocean, so stay tuned and make sure to like and subscribe!"
                )
            }
        ]
    }
]

# Backward compatibility alias
TECH_FACTS_DATABASE = [p for s in FALLBACK_SERIES_DATABASE for p in s["parts"]]


BANNED_META_PHRASES = [
    "in this series",
    "in this video we",
    "we will delve",
    "we'll delve",
    "we will explore",
    "we'll explore",
    "we'll cover it all",
    "we will cover it all",
    "we're about to dive",
    "we will dive into",
    "delve into the world",
    "let's talk about the",
    "let us talk about",
    "in our final part, we'll explore"
]


def validate_series_quality(series_data: dict) -> bool:
    """
    Strictly validates that generated series is high-depth, rich, and free of shallow meta-talk.
    """
    if not series_data or not isinstance(series_data, dict):
        return False
    parts = series_data.get("parts", [])
    if len(parts) < 3:
        log("⚠️ Quality check failed: Series has fewer than 3 parts.")
        return False

    for p in parts:
        script = p.get("script", "").strip()
        word_count = len(script.split())
        
        # 1. Word count check: Must be 125-165 words for true depth (50-55s spoken)
        if word_count < 125:
            log(f"⚠️ Quality check failed: Part {p.get('part_number')} script too short ({word_count} words < 125 words). Needs more technical explanation.")
            return False
            
        # 2. Anti-meta check: Must not contain hollow filler phrases
        script_lower = script.lower()
        for banned in BANNED_META_PHRASES:
            if banned in script_lower:
                log(f"⚠️ Quality check failed: Part {p.get('part_number')} contains hollow meta-talk ('{banned}'). Must directly explain real facts.")
                return False
                
        # 3. Call-to-action check
        if not ("like" in script_lower or "subscribe" in script_lower):
            log(f"⚠️ Quality check failed: Part {p.get('part_number')} missing CTA.")
            return False

    return True


def query_opencode_deepseek(system_prompt: str, user_prompt: str, max_tokens: int = 2500, temperature: float = 0.75) -> dict:
    """
    Priority 1: Queries OpenCode DeepSeek v4 Flash (CLI or HTTP API) with strict quality validation.
    """
    import subprocess
    import shutil
    from main import parse_llm_json

    # 1. Try local OpenCode CLI if available
    opencode_bin = shutil.which("opencode") or str(Path.home() / ".opencode/bin/opencode")
    if opencode_bin and Path(opencode_bin).exists():
        try:
            log("🧠 Querying OpenCode DeepSeek v4 Flash via OpenCode CLI (Priority 1)...")
            full_prompt = (
                f"{system_prompt}\n\n"
                f"{user_prompt}\n\n"
                "Return ONLY a single valid raw JSON object. No conversational preamble, no markdown wrappers."
            )
            res = subprocess.run(
                [opencode_bin, "run", "-m", "opencode/deepseek-v4-flash-free", full_prompt],
                capture_output=True,
                text=True,
                timeout=60
            )
            if res.returncode == 0 and res.stdout:
                parsed = parse_llm_json(res.stdout)
                if validate_series_quality(parsed):
                    log(f"✅ OpenCode DeepSeek v4 Flash successfully generated in-depth series: '{parsed.get('topic')}' ({len(parsed['parts'])} Parts)")
                    return parsed
        except Exception as oe:
            log(f"⚠️ OpenCode CLI execution notice: {oe}")

    # 2. Try HTTP endpoints with OPENCODE_API_KEY / DEEPSEEK_API_KEY
    opencode_key = os.environ.get("OPENCODE_API_KEY") or os.environ.get("DEEPSEEK_API_KEY") or os.environ.get("OPENROUTER_API_KEY")
    if not opencode_key:
        return None

    import urllib.request

    base_url = os.environ.get("OPENCODE_BASE_URL")
    endpoints = []
    
    if base_url:
        endpoints.append((base_url, ["opencode/deepseek-v4-flash-free", "deepseek-v4-flash", "deepseek-chat"]))
    
    endpoints.extend([
        ("https://api.opencode.ai/v1/chat/completions", ["opencode/deepseek-v4-flash-free", "deepseek-v4-flash", "deepseek-ai/deepseek-v4-flash"]),
        ("https://api.deepseek.com/chat/completions", ["deepseek-chat", "deepseek-reasoner"]),
        ("https://openrouter.ai/api/v1/chat/completions", ["deepseek/deepseek-v4-flash", "deepseek/deepseek-chat", "deepseek/deepseek-r1"])
    ])

    for url, model_list in endpoints:
        for model in model_list:
            try:
                host_label = url.split("/")[2]
                log(f"🧠 Querying OpenCode DeepSeek v4 Flash (Priority 1: {model} @ {host_label})...")
                payload = json.dumps({
                    "model": model,
                    "messages": [
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt}
                    ],
                    "temperature": temperature,
                    "max_tokens": max_tokens
                }).encode("utf-8")

                req = urllib.request.Request(
                    url,
                    data=payload,
                    headers={
                        "Authorization": f"Bearer {opencode_key}",
                        "Content-Type": "application/json",
                        "HTTP-Referer": "https://github.com/auto-clipper-shorts",
                        "X-Title": "Auto Clipper Shorts"
                    }
                )
                with urllib.request.urlopen(req, timeout=40) as resp:
                    data = json.loads(resp.read().decode("utf-8"))
                    raw_text = data["choices"][0]["message"]["content"]
                    parsed = parse_llm_json(raw_text)
                    if validate_series_quality(parsed):
                        log(f"✅ OpenCode DeepSeek v4 Flash successfully generated in-depth series: '{parsed.get('topic')}' ({len(parsed['parts'])} Parts)")
                        return parsed
            except Exception as e:
                log(f"⚠️ OpenCode DeepSeek notice ({model}): {e}")
                continue
    return None


def query_groq_fallback(system_prompt: str, user_prompt: str) -> dict:
    """
    Priority 2 & 3 Fallback: Groq Llama-3.3-70B and Llama-3.1-8B with strict quality validation.
    """
    groq_api_key = os.environ.get("GROQ_API_KEY")
    if not groq_api_key:
        return None

    try:
        from groq import Groq
        from main import parse_llm_json
        client = Groq(api_key=groq_api_key)
        
        # Priority 2: Llama-3.3-70B | Priority 3: Llama-3.1-8B
        for model_name in ["llama-3.3-70b-versatile", "llama-3.1-8b-instant"]:
            try:
                log(f"🦙 Querying Groq Fallback ({model_name})...")
                resp = client.chat.completions.create(
                    model=model_name,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt}
                    ],
                    response_format={"type": "json_object"},
                    temperature=0.75,
                    max_tokens=2500
                )
                raw_text = resp.choices[0].message.content
                series_data = parse_llm_json(raw_text)
                if validate_series_quality(series_data):
                    log(f"✅ Groq ({model_name}) successfully generated in-depth series: '{series_data.get('topic')}' ({len(series_data['parts'])} Parts)")
                    return series_data
            except Exception as me:
                log(f"⚠️ Groq model {model_name} notice: {me}")
                continue
    except Exception as ge:
        log(f"⚠️ Groq dynamic series generation error: {ge}")

    return None


def generate_dynamic_series_with_groq(history: dict = None) -> dict:
    """
    Generates an in-depth, thorough multi-part series (3-5 parts) on ONE technical topic:
    1. OpenCode DeepSeek v4 Flash (Priority 1)
    2. Groq Llama-3.3-70B (Priority 2 Fallback)
    3. Groq Llama-3.1-8B (Priority 3 Fallback)
    4. Database Catalog (Safety Net)
    """
    past_topics = []
    if history:
        past_topics = history.get("ai_past_topics", [])[-15:]

    system_prompt = (
        "You are an elite, world-class technical documentary storyteller (like Veritasium, Fireship, and Kurzgesagt).\n"
        "Your mission is to create a deeply technical, high-retention 3-part masterclass series on ONE fascinating engineering, programming, or computer science subject.\n"
        "STRICT CONTENT & ANTI-SLOP RULES (CRITICAL):\n"
        "1. NO META-TALK OR INTRO FILLER: NEVER say 'in this video we will explore', 'in this series we delve', 'from X to Y we cover it all', or 'let us talk about'. NEVER tease a topic without explaining it immediately. Dive STRAIGHT into the real technical mechanisms, numbers, hardware, or code from word one!\n"
        "2. EXPLAIN THE REAL MECHANISMS IN FULL DETAIL: Every part must explain the actual technical science: exact math, algorithms, protocols, memory registers, voltages, frequencies, physical constraints, historical disasters, or dollar losses.\n"
        "3. WORD COUNT: Every single part script MUST be between 135 and 155 spoken words (~50 to 55 seconds spoken narration). Never generate short, rushed summaries.\n"
        "4. NARRATIVE PROGRESSION ACROSS 3 PARTS:\n"
        "   - Part 1: Concrete Paradox & The Core Mechanism (Hook + Deep explanation of why this is counter-intuitive + Cliffhanger for Part 2 + 'Like and subscribe for Part 2!').\n"
        "   - Part 2: Under-The-Hood Architecture & Real-World Engineering (Exact step-by-step mechanism, algorithms, physical hardware + Cliffhanger for Part 3 + 'Like and subscribe for Part 3!').\n"
        "   - Part 3 (Finale): Real-World Catastrophe, Legendary Glitch, or Modern Breakthrough + Master Takeaway + Next Series Teaser + 'Like and subscribe to stay tuned!'.\n"
        "5. Spoken English: Pure natural spoken text for TTS. No markdown symbols, no raw URLs."
    )

    user_prompt = f"""
Generate an in-depth 3-Part Tech Masterclass Series with zero meta-talk.
Avoid repeating any of these recent topics: {json.dumps(past_topics)}

JSON Output Schema:
{{
  "topic": "<Core topic name in ALL CAPS, e.g. 'HOW WI-FI SEES THROUGH WALLS'>",
  "badge_base": "<Short 2-3 word badge with emoji, e.g. 'WI-FI RADAR 📡' or 'QUANTUM SECRETS 💻'>",
  "next_topic_teaser": "<Short teaser of what the next upcoming series will explore, e.g. 'the secret Linux kernel memory management algorithms'>",
  "total_parts": 3,
  "parts": [
    {{
      "part_number": 1,
      "title": "<Catchy title under 65 chars including '• Part 1' and #Shorts #TechShorts>",
      "badge": "<badge_base> • PART 1",
      "voice": "en-US-ChristopherNeural",
      "tags": ["techshorts", "technology", "part1", "shorts", "developer"],
      "script": "<EXACTLY 135-155 words directly explaining the core technical concept and ending with cliffhanger for Part 2 + 'Like and subscribe for Part 2!'>"
    }},
    {{
      "part_number": 2,
      "title": "<Catchy title under 65 chars including '• Part 2' and #Shorts #TechShorts>",
      "badge": "<badge_base> • PART 2",
      "voice": "en-US-ChristopherNeural",
      "tags": ["techshorts", "technology", "part2", "shorts", "developer"],
      "script": "<EXACTLY 135-155 words explaining the deeper inner architecture and ending with cliffhanger for Part 3 + 'Like and subscribe for Part 3!'>"
    }},
    {{
      "part_number": 3,
      "title": "<Catchy title under 65 chars including '• Part 3' and #Shorts #TechShorts>",
      "badge": "<badge_base> • PART 3",
      "voice": "en-US-ChristopherNeural",
      "tags": ["techshorts", "technology", "part3", "shorts", "developer"],
      "script": "<EXACTLY 135-155 words delivering the master resolution, giving the next-topic teaser, and ending with 'stay tuned and make sure to like and subscribe!'>"
    }}
  ]
}}
"""
    # Priority 1: OpenCode DeepSeek v4 Flash
    series = query_opencode_deepseek(system_prompt, user_prompt)
    if series:
        return series

    # Priority 2 & 3: Groq Llama-3.3-70B & 8B Fallback
    log("⚠️ OpenCode DeepSeek limit reached or unavailable. Falling back to Groq Llama-3.3-70B (Priority 2)...")
    series = query_groq_fallback(system_prompt, user_prompt)
    if series:
        return series

    return None


async def synthesize_tech_audio(script_text: str, output_mp3: Path, voice: str = "en-US-ChristopherNeural", rate: str = "+10%"):
    """Synthesizes high quality voice narration and returns word-timed segments with automatic retry."""
    if not edge_tts:
        raise RuntimeError("edge-tts is not installed. Run `pip install edge-tts`")

    log(f"🎙️ Synthesizing tech narration voice using {voice} (rate: {rate})...")
    voices_to_try = [voice, "en-US-GuyNeural", "en-US-EricNeural", "en-US-AndrewNeural", "en-US-BrianNeural"]
    sentences = []
    
    for v in voices_to_try:
        try:
            comm = edge_tts.Communicate(script_text, voice=v, rate=rate)
            sentences = []
            with open(output_mp3, "wb") as f:
                async for chunk in comm.stream():
                    if chunk["type"] == "audio":
                        f.write(chunk["data"])
                    elif chunk["type"] in ("SentenceBoundary", "WordBoundary"):
                        s = chunk["offset"] / 10_000_000
                        d = chunk["duration"] / 10_000_000
                        sentences.append({"text": chunk["text"], "start": s, "end": s + d})
            if output_mp3.exists() and output_mp3.stat().st_size > 10000:
                break
        except Exception as e:
            log(f"TTS retry with alternate voice {v}: {e}")
            await asyncio.sleep(1.0)
            continue

    # If sentence boundaries weren't returned, fallback to total audio duration estimation
    if not sentences and output_mp3.exists():
        import subprocess
        probe_cmd = ["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "default=noprint_wrappers=1:nokey=1", str(output_mp3)]
        res = subprocess.run(probe_cmd, capture_output=True, text=True)
        total_dur = float(res.stdout.strip() or 50.0)
        sentences = [{"text": script_text, "start": 0.0, "end": total_dur}]

    segments = []
    for idx, s in enumerate(sentences):
        words = create_word_timestamps_from_segment(s["text"], s["start"], s["end"])
        segments.append({
            "id": idx,
            "start": s["start"],
            "end": s["end"],
            "text": s["text"],
            "words": words
        })

    return segments


def generate_dynamic_tech_fact_with_groq(history: dict = None) -> dict:
    """
    Uses Groq Llama-3.3-70B (or fallback models) to dynamically invent a brand new,
    viral, mind-blowing tech story / developer tip short (~50-55s / ~140 words).
    Falls back to TECH_FACTS_DATABASE if Groq is unavailable.
    """
    groq_api_key = os.environ.get("GROQ_API_KEY")
    if not groq_api_key:
        return None

    past_topics = []
    if history:
        past_topics = history.get("ai_past_topics", [])[-15:]

    system_prompt = (
        "You are an elite viral tech short-form storyteller (like Veritasium, Fireship, Kurzgesagt, and Cleo Abram).\n"
        "Your mission is to generate a deeply fascinating, mind-blowing tech story, programming secret, "
        "hardware mystery, cybersecurity breakdown, or computer science paradox for YouTube Shorts.\n"
        "CRITICAL RULES:\n"
        "1. Duration & Word Count: The script MUST be between 130 and 155 spoken words (~50 to 55 seconds spoken duration).\n"
        "2. Structure: 3-Act structure: (Act 1: Attention-grabbing hook/paradox) -> (Act 2: Deep technical explanation with real history/numbers/mechanisms) -> (Act 3: Mind-blowing takeaway & CTA).\n"
        "3. Spoken English: Write natural spoken English suitable for TTS narration. Do not use markdown, raw URLs, or code blocks in the script. Spell out numbers or acronyms where helpful.\n"
        "4. Tone: High-energy, authoritative, thrilling, and educational."
    )

    user_prompt = f"""
Generate a completely fresh, exciting Tech Short concept.
Avoid repeating any of these recent topics: {json.dumps(past_topics)}

JSON Output Schema:
{{
  "topic": "<Short 3-5 word header in ALL CAPS, e.g. 'HOW WI-FI SEES THROUGH WALLS'>",
  "badge": "<Short 2-3 word badge with emoji, e.g. 'TECH SECRET ⚡' or 'CYBERSECURITY 🛡️' or 'CS FACT 💻'>",
  "title": "<Viral YouTube Shorts title under 65 chars ending with #Shorts #TechShorts>",
  "voice": "<One of: 'en-US-ChristopherNeural', 'en-US-GuyNeural', 'en-US-EricNeural'>",
  "tags": ["techshorts", "technology", "programming", "coding", "developer", "shorts"],
  "script": "<The complete 130-155 word narration script (~50-55 seconds)>"
}}
"""
    log("🧠 Generating fresh viral tech topic with Groq Llama-3.3-70B...")
    try:
        from groq import Groq
        from main import parse_llm_json
        client = Groq(api_key=groq_api_key)
        for model_name in ["llama-3.3-70b-versatile", "llama-3.1-8b-instant"]:
            try:
                resp = client.chat.completions.create(
                    model=model_name,
                    messages=[
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_prompt}
                    ],
                    response_format={"type": "json_object"},
                    temperature=0.75,
                    max_tokens=800
                )
                raw_text = resp.choices[0].message.content
                fact_data = parse_llm_json(raw_text)
                
                if fact_data.get("script") and len(fact_data["script"].split()) >= 80:
                    log(f"✅ Groq generated dynamic topic: {fact_data.get('topic')} ({fact_data.get('badge')})")
                    return fact_data
            except Exception as me:
                log(f"⚠️ Groq model {model_name} notice: {me}")
                continue
    except Exception as ge:
        log(f"⚠️ Groq dynamic generation error: {ge}")
        
    return None


def render_tech_short(fact_index: int = None, dry_run: bool = False):
    log("=======================================================")
    log(" 🎬 Generating Multi-Part Tech Story Short (TTS Narration)")
    log("=======================================================")

    history = load_json(HISTORY_PATH, {
        "last_series_index": -1,
        "active_series": None,
        "completed_series": [],
        "ai_past_topics": []
    })

    active_series = history.get("active_series")
    
    # Check if we need to start a fresh series:
    needs_new_series = False
    if not active_series:
        needs_new_series = True
    elif not active_series.get("parts"):
        needs_new_series = True
    elif active_series.get("current_part_index", 0) >= len(active_series.get("parts", [])):
        needs_new_series = True

    if fact_index is not None and 0 <= fact_index < len(TECH_FACTS_DATABASE):
        # Override mode: render specific isolated fact
        fact = TECH_FACTS_DATABASE[fact_index]
        part_info = fact
        series_topic = fact.get("topic", "TECH FACT")
        log(f"Selected Explicit Topic [{fact_index + 1}/{len(TECH_FACTS_DATABASE)}]: {fact['topic']} ({fact['badge']})")
    else:
        if needs_new_series:
            log("🔄 No active series in progress. Starting a brand new deep-dive tech series...")
            # Try Groq first for dynamic series
            new_series = generate_dynamic_series_with_groq(history)
            if new_series and new_series.get("parts"):
                active_series = new_series
                active_series["current_part_index"] = 0
                past_list = history.get("ai_past_topics", [])
                past_list.append(active_series["topic"])
                history["ai_past_topics"] = past_list[-30:]
            else:
                last_s_idx = history.get("last_series_index", -1)
                next_s_idx = (last_s_idx + 1) % len(FALLBACK_SERIES_DATABASE)
                active_series = json.loads(json.dumps(FALLBACK_SERIES_DATABASE[next_s_idx]))
                active_series["current_part_index"] = 0
                history["last_series_index"] = next_s_idx
                log(f"Selected Fallback Series [{next_s_idx + 1}/{len(FALLBACK_SERIES_DATABASE)}]: {active_series['topic']}")
            
            history["active_series"] = active_series

        # Retrieve current part to render
        part_idx = active_series.get("current_part_index", 0)
        parts_list = active_series.get("parts", [])
        if part_idx >= len(parts_list):
            part_idx = 0
            active_series["current_part_index"] = 0
            
        part_info = parts_list[part_idx]
        total_p = len(parts_list)
        series_topic = active_series.get("topic", "TECH DEEP DIVE")
        log(f"🎬 Series: '{series_topic}' ➔ Rendering Part {part_info.get('part_number', part_idx + 1)} of {total_p}...")

    # Output directories
    home_downloads = Path.home() / "downloads" / "auto_clipper_output"
    phone_downloads = Path.home() / "storage" / "downloads" / "auto_clipper_output"
    home_downloads.mkdir(parents=True, exist_ok=True)
    try:
        phone_downloads.mkdir(parents=True, exist_ok=True)
    except Exception:
        pass

    voice_mp3 = OUTPUT_DIR / "tech_narration.mp3"
    
    # 1. Synthesize Audio Narration with exact word timestamps
    segments = asyncio.run(synthesize_tech_audio(part_info["script"], voice_mp3, voice=part_info.get("voice", "en-US-ChristopherNeural")))
    start_sec = 0.0
    # Add comfortable 1.8s post-speech buffer so YouTube loop playback never clips the final words
    last_word_end = segments[-1]["end"] if segments else 10.0
    end_sec = last_word_end + 1.8
    duration = end_sec - start_sec

    log(f"✅ Tech voice synthesis complete ({duration:.1f}s narration across {len(segments)} segments).")

    # 2. Generate Neon Karaoke ASS Subtitles
    ass_path = OUTPUT_DIR / "tech_fact_subtitles.ass"
    generate_karaoke_ass_subtitles(segments, start_sec, end_sec, ass_path)

    # 3. Render 1080x1920 Short via Studio Visualizer
    out_video = OUTPUT_DIR / "tech_fact_short.mp4"
    log("🎨 Rendering 1080x1920 portrait Short with Studio Layout...")
    render_studio_visualizer_short(
        audio_full_path=voice_mp3,
        start_sec=start_sec,
        end_sec=end_sec,
        ass_subtitle_path=ass_path,
        output_final_path=out_video,
        speaker_badge=part_info.get("badge", "TECH FACT 💡"),
        transcript_segments=segments,
        speaker_gender="male",
        host_gender="male",
        topic_title=series_topic,
        video_reference_path=None
    )

    if out_video.exists() and out_video.stat().st_size > 50000:
        size_mb = out_video.stat().st_size / (1024 * 1024)
        log(f"✅ Tech Short generated successfully! ({size_mb:.2f} MB)")

        dest_1 = home_downloads / "tech_fact_short.mp4"
        shutil.copy2(out_video, dest_1)
        log(f"📁 Copied to: {dest_1}")

        if phone_downloads.exists():
            try:
                dest_2 = phone_downloads / "tech_fact_short.mp4"
                shutil.copy2(out_video, dest_2)
                log(f"📱 Copied to Phone Downloads: {dest_2}")
            except Exception as e:
                log(f"Phone copy notice: {e}")

        # 4. Upload to YouTube if not dry-run
        if not dry_run:
            clip_info = {
                "viral_title": part_info["title"],
                "speaker_badge": part_info.get("badge", "TECH FACT 💡"),
                "tags": part_info.get("tags", ["techshorts", "coding", "techfacts", "shorts", "technology"])
            }
            podcast_dummy = {
                "name": "Tech Facts & Developer Tips",
                "default_tags": ["techshorts", "technology", "programming", "shorts", "developer", "coding"],
                "attribution_template": "Curated by @woosclips ⚡ Subscribe for daily tech revelations!"
            }
            log(f"🚀 Uploading Short to YouTube channel @woosclips: {part_info['title']}...")
            upload_to_youtube(out_video, clip_info, podcast_dummy, original_video_url="https://youtube.com/@woosclips")

        # 5. Advance Series State Rotation
        if fact_index is None and active_series:
            next_part = active_series.get("current_part_index", 0) + 1
            if next_part >= len(active_series.get("parts", [])):
                log(f"🎉 Series '{active_series.get('topic')}' concluded ({len(active_series['parts'])}/{len(active_series['parts'])} Parts complete)!")
                completed = history.get("completed_series", [])
                completed.append({
                    "topic": active_series.get("topic"),
                    "total_parts": len(active_series.get("parts", [])),
                    "completed_at": str(Path.cwd())
                })
                history["completed_series"] = completed[-20:]
                history["active_series"] = None  # Ready to start next topic on next run!
            else:
                active_series["current_part_index"] = next_part
                history["active_series"] = active_series
                log(f"📌 Series state saved: next run will render Part {next_part + 1} of {len(active_series['parts'])}.")

        save_json(HISTORY_PATH, history)

        log("=======================================================")
        log(f" 🎉 Video Ready: {part_info['title']}")
        log("=======================================================")
    else:
        log("❌ Video generation failed or output file is empty.")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Generate and upload Multi-Part Tech Story Shorts.")
    parser.add_argument("index", nargs="?", type=int, default=None, help="Explicit fact index (optional override)")
    parser.add_argument("--dry-run", action="store_true", help="Generate video without uploading")
    parser.add_argument("--index", dest="fact_idx", type=int, default=None, help="Explicit fact index")
    args = parser.parse_args()

    chosen_index = args.fact_idx if args.fact_idx is not None else args.index
    render_tech_short(chosen_index, dry_run=args.dry_run)
